### ISSUE TITLE
Follow _ENV of parent scopes

### ISSUE THREAD

**Issue by daurnimator** [hishamhm/f-strings#3]
```
local assert = assert
local _ENV = {x = "foo"}
assert("foo" == x)
assert("foo" == F'{x}')
```

I pushed some tests on a branch: https://github.com/daurnimator/f-strings/blob/master/spec/F_spec.lua

**Comment by hishamhm** [comment]
Fixed! Thanks for the tests! I added the spec file (sorry about being clumsy and not merging properly).

Now every case works except for unreferenced upvalues. I think we really can't do that. :\

**Comment by daurnimator** [comment]
> Fixed! Thanks for the tests! I added the spec file (sorry about being clumsy and not merging properly).

I don't think you did? (at least I can't see it in the github browser?)
btw, you can get github to do the merge for you by creating a pull request (https://github.com/hishamhm/f-strings/compare/master...daurnimator:master) and clicking "merge".
